import { useState } from "react"
import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"

// Data...
import { formInputsCheckbox, formInputsRadio } from "_data/form-data"

// Components...
import InputCheckbox from "components/InputCheckbox"
import InputRadio from "components/InputRadio"

const Home: NextPage = () => {
	const checkboxValues = formInputsCheckbox.reduce<any>(
		(prevValue, input) => ({...prevValue, [input.name]: input.value }),
		{}
	)
  const radioValues = formInputsRadio.reduce<any>((prevValue, input) => ({...prevValue, [input.name]: input.value }), {})
  
	console.log("Home rendering !! ", checkboxValues, radioValues)
	const [values, setValues] = useState<any>({
		...checkboxValues,
		...radioValues
	})

	const handleChange = (name: string, value: any) => {
		setValues((prevValues: any) => ({ ...prevValues, [name]: value }))
		console.log("handleChange called !! ", values)
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{formInputsCheckbox.map((input) => (
				<InputCheckbox
					handleChange={(e: any) => handleChange(input.name, e.currentTarget.checked)}
					{...input}
					value={values[input.name]}
				/>
			))}
			{formInputsRadio.map((input) => (
				<InputRadio
					handleChange={(e: any) => handleChange(input.name, e.currentTarget.value)}
					{...input}
					value={values[input.name]}
				/>
			))}
		</div>
	)
}

export default Home
